# Generated by Django 4.2.1 on 2023-07-22 12:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_player', models.IntegerField(default=0, verbose_name='Ходящий')),
                ('number_of_players', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)], verbose_name='Количество игроков (2-4)')),
                ('number_of_players_connected', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Количество игроков (2-4) подключено')),
                ('max_number_of_questions', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100), django.core.validators.StepValueValidator(10)], verbose_name='Максимальное количество вопросов')),
                ('question_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='ID вопроса')),
                ('is_started', models.BooleanField(default=False, verbose_name='Начата')),
                ('is_over', models.BooleanField(default=False, verbose_name='Завершена')),
                ('datetime_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'игра',
                'verbose_name_plural': 'игры',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_question', models.CharField(choices=[('Б', 'Биология'), ('Г', 'География'), ('И', 'История')], default='Б', max_length=1, verbose_name='Тип вопроса')),
                ('question', models.TextField(blank=True, max_length=256, verbose_name='Вопрос')),
                ('answer_correct', models.CharField(blank=True, max_length=32, verbose_name='Верный ответ')),
                ('answer_2', models.CharField(blank=True, max_length=32, verbose_name='Второй ответ')),
                ('answer_3', models.CharField(blank=True, max_length=32, verbose_name='Третий ответ')),
                ('answer_4', models.CharField(blank=True, max_length=32, verbose_name='Четвертый ответ')),
                ('datetime_addition', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время добавления')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_played', models.BooleanField(default=False, verbose_name='Играет')),
                ('current_position', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Текущее положение')),
                ('number_move', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Порядкойвый номер в текущей игре')),
                ('number_of_points', models.IntegerField(default=0, verbose_name='Количество очков')),
                ('number_of_questions_received', models.IntegerField(default=0, verbose_name='Кол-во ответов')),
                ('number_of_correct_answers', models.IntegerField(default=0, verbose_name='Кол-во верных ответов')),
                ('skipping_move', models.BooleanField(default=False, verbose_name='Пропуск хода')),
                ('thinks_about_the_question', models.BooleanField(default=False, verbose_name='Думает над вопросом')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'игрок',
                'verbose_name_plural': 'игроки',
            },
        ),
        migrations.CreateModel(
            name='HistoryMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_history', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Номер истории')),
                ('number_move', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)], verbose_name='Номер ходящего')),
                ('number_steps', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Количество шагов')),
                ('datetime_addition', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время добавления')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.game')),
            ],
            options={
                'verbose_name': 'история',
                'verbose_name_plural': 'истории',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='first_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_player', to='main_site.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='fourth_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_player', to='main_site.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='second_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_player', to='main_site.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='third_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_player', to='main_site.player'),
        ),
    ]
