# Generated by Django 5.0 on 2024-08-30 22:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_site", "0005_alter_player_number_of_questions_received"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historymove",
            old_name="game_id",
            new_name="game",
        ),
    ]
